### ISSUE TITLE
classMethods静态方法无法调用

### ISSUE THREAD

**Issue by NeverSa** [caiya/node-sequelize#1]
为什么我在模型中定义的静态方法，在导入调用的时候不行呢

**Comment by caiya** [comment]
@NeverSa 因为sequlize4 api有变动，具体参考模型定义一栏中的模型拓展下说明，去除了静态方法的配置而改为直接和类定义静态方法类似方式来添加静态方法了。http://docs.sequelizejs.com/manual/tutorial/models-definition.html

**Comment by fuweimin** [comment]
谢谢了
